import { test } from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync, readdirSync } from 'node:fs';
import worker from '../dist/server/index.js';
import { digest, passwordHash } from '../worker/auth.js';

function database() {
  const db = new DatabaseSync(':memory:');
  for (const file of readdirSync(new URL('../drizzle/', import.meta.url)).filter(f => f.endsWith('.sql')).sort()) db.exec(readFileSync(new URL(`../drizzle/${file}`, import.meta.url), 'utf8'));
  const prepare = sql => ({ bind(...args) {
    const statement = db.prepare(sql);
    return { first: () => statement.get(...args) || null, all: () => ({ results: statement.all(...args) }), run: () => ({ meta: { changes: Number(statement.run(...args).changes) } }) };
  } });
  return { prepare, batch: async statements => { db.exec('BEGIN'); try { const results = statements.map(s => s.run()); db.exec('COMMIT'); return results; } catch(e) { db.exec('ROLLBACK'); throw e; } }, db };
}
test('authorization and the full reservation lifecycle', async () => {
  const DB = database(), env = { DB, OWNER_SETUP_TOKEN: 'private-owner-setup-token', ASSETS: { fetch: () => new Response('asset') } };
  // Previously blocked accounts and IPs must remain usable after removing the caps.
  for (const key of [`auth:${await digest('local')}`, `email:${await digest('student@test.com')}`, 'write:platform-owner', 'reset:platform-owner']) {
    DB.db.prepare('INSERT INTO limits (key,count,expires) VALUES (?,?,?)').run(key, 9999, Date.now() + 86400000);
  }
  const clients = {};
  async function call(who, path, data, expected = 200, headers = {}) {
    const request = new Request(`https://mansah.test/api/${path}`, { method: data === undefined ? 'GET' : 'POST', headers: { cookie: clients[who] || '', ...(data === undefined ? {} : { origin: 'https://mansah.test', 'content-type': 'application/json' }), ...headers }, ...(data === undefined ? {} : { body: JSON.stringify(data) }) });
    const response = await worker.fetch(request, env);
    const body = await response.json();
    if (body.error) assert.doesNotMatch(body.error, /[\u00d8\u00d9\ufffd]/, 'Error messages must contain readable Arabic');
    assert.equal(response.status, expected, `${path}: ${JSON.stringify(body)}`);
    if (response.headers.has('set-cookie')) clients[who] = response.headers.get('set-cookie').split(';')[0];
    return body;
  }
  const credentials = (email, role) => ({ email, role, password: 'Long-test-password-123', name: role });
  await call('guest', 'admin/users', undefined, 401);
  await call('guest', 'auth/register', credentials('evil@test.com', 'admin'), 403);
  await call('guest', 'auth/setup', { ...credentials('owner@test.com', 'admin'), token: 'wrong' }, 403);
  await call('owner', 'auth/setup', { ...credentials('owner@test.com', 'admin'), token: env.OWNER_SETUP_TOKEN });
  await call('guest', 'auth/setup', { ...credentials('owner2@test.com', 'admin'), token: env.OWNER_SETUP_TOKEN }, 409);
  const teacher = (await call('teacher', 'auth/register', credentials('teacher@test.com', 'teachers'))).user;
  const student = (await call('student', 'auth/register', credentials('student@test.com', 'students'))).user;
  await call('other', 'auth/register', credentials('other@test.com', 'students'));
  await call('teacher', 'teachers/slots', undefined, 403);
  await call('teacher', 'teachers/profile', { name: 'Teacher', subject: 'Math', bio: 'Algebra tutor' });
  await call('student', 'admin/users', undefined, 401);
  await call('student', 'teachers/slots', undefined, 401);
  await call('owner', `admin/users/${teacher.id}`, { status: 'active' });
  await call('teacher', 'auth/login', credentials('teacher@test.com', 'teachers'));
  const originalCatalog = (await call('student', 'students/catalog')).categories;
  assert.equal(originalCatalog.length, 6);
  await call('teacher', 'teachers/catalog', { action: 'delete', id: 'jordan' }, 403);
  await call('student', 'students/catalog', { action: 'save' }, 403);
  const draft = { name: 'تصنيف جديد', description: 'وصف عربي', icon: 'EN', levels: ['مبتدئ'], subjects: ['مادة جديدة'] };
  const added = (await call('owner', 'admin/catalog', { action: 'save', ...draft })).categories;
  const card = added.find(row => row.name === draft.name);
  assert.ok(card);
  const ids = added.map(row => row.id).reverse();
  await call('owner', 'admin/catalog', { action: 'reorder', ids });
  assert.deepEqual((await call('teacher', 'teachers/catalog')).categories.map(row => row.id), ids);
  await call('owner', 'admin/catalog', { action: 'reorder', ids: ['missing'] }, 409);
  await call('owner', 'admin/catalog', { action: 'save', ...draft, id: card.id, name: 'تصنيف معدل' });
  assert.equal((await call('student', 'students/catalog')).categories[0].name, 'تصنيف معدل');
  assert.deepEqual((await call('teacher', 'teachers/catalog')).categories[0].subjects, draft.subjects);
  await call('owner', 'admin/catalog', { action: 'delete', id: card.id });
  assert.equal((await call('student', 'students/catalog')).categories.length, 6);
  await call('owner', 'admin/catalog', { action: 'reorder', ids: originalCatalog.map(row => row.id) });
  await call('teacher', 'teachers/home');
  await call('teacher', 'teachers/available');
  await call('teacher', 'teachers/booked');
  await call('teacher', 'teachers/history');
  const missing = await call('teacher', 'teachers/missing-page', undefined, 404);
  assert.equal(missing.error, 'الطلب غير موجود أو غير متاح لحسابك.');
  await call('student', 'auth/login', credentials('student@test.com', 'admin'), 401);
  await call('teacher', 'teachers/slots', { start: Date.now() - 1000, minutes: 60, price: 1500, subject: 'Math' }, 400);
  const activeRangeStart = Date.now() - 7200000;
  await call('teacher', 'teachers/slots', { start: activeRangeStart, available_until: Date.now() + 60000, minutes: 60, price: 1500, subject: 'Active range' });
  const activeRange = (await call('student', 'students/slots')).slots.find(row => row.subject === 'Active range');
  assert.ok(activeRange, 'an availability range that already started but has not ended must be visible');
  await call('teacher', `teachers/slots/${activeRange.id}`, {});
  const start = Date.now() + 300000;
  await call('teacher', 'teachers/slots', { start, minutes: 60, price: 1500, subject: 'Math' });
  await call('teacher', 'teachers/slots', { start: start + 60000, minutes: 60, price: 1500, subject: 'Math' }, 409);
  const slot = (await call('student', 'students/slots')).slots[0];
  DB.db.prepare('UPDATE slots SET start=?,available_until=? WHERE id=?').run(Date.now() - 300000, Date.now() + 3600000, slot.id);
  assert.ok((await call('student', 'students/slots')).slots.some(row => row.id === slot.id), 'an active availability range must remain visible to students');
  const reservation = await call('student', `students/slots/${slot.id}`, {});
  DB.db.prepare('UPDATE slots SET start=?,available_until=? WHERE id=?').run(start, start + 3600000, slot.id);
  await call('other', `students/slots/${slot.id}`, {}, 409);
  assert.equal((await call('other', 'students/overview')).bookings.length, 0);
  assert.equal((await call('teacher', 'teachers/overview')).bookings.length, 1);
  assert.equal((await call('teacher', 'teachers/reminders')).bookings.length, 1);
  assert.equal((await call('other', 'students/reminders')).bookings.length, 0);
  await call('owner', 'admin/reminders', undefined, 404);
  assert.ok(!(await call('student', 'students/overview')).bookings[0].room);
  assert.equal((await call('student', 'students/rooms')).bookings.length, 1);
  assert.equal((await call('teacher', 'teachers/rooms')).bookings.length, 1);
  await call('other', `students/bookings/${reservation.id}/room`, undefined, 404);
  await call('owner', `admin/bookings/${reservation.id}/room`, undefined, 403);
  const studentRoom = await call('student', `students/bookings/${reservation.id}/room`);
  assert.equal(studentRoom.room, (await call('teacher', `teachers/bookings/${reservation.id}/room`)).room);
  assert.equal((await call('student', `students/bookings/${reservation.id}/presence`)).teacherLive, false);
  const teacherPresence = await call('teacher', `teachers/bookings/${reservation.id}/presence`, { active: true, peerId: 'teacher-session-1' });
  assert.equal(teacherPresence.teacherLive, true);
  assert.equal(teacherPresence.teacherPeerId, 'teacher-session-1');
  const studentViewOfPresence = await call('student', `students/bookings/${reservation.id}/presence`);
  assert.equal(studentViewOfPresence.teacherLive, true);
  assert.equal(studentViewOfPresence.teacherPeerId, 'teacher-session-1');
  assert.equal((await call('teacher', `teachers/bookings/${reservation.id}/presence`, { active: false })).teacherLive, false);
  DB.db.prepare('UPDATE slots SET start=? WHERE id=?').run(Date.now() - 2 * 86400000, slot.id);
  assert.equal((await call('student', `students/bookings/${reservation.id}/room`)).room, studentRoom.room);
  DB.db.prepare('UPDATE slots SET start=? WHERE id=?').run(start, slot.id);
  await call('student', `students/bookings/${reservation.id}/payment`, { paid: 1, reference: 'fake' }, 404);
  await call('teacher', `teachers/bookings/${reservation.id}/notes`, { notes: 'Homework', resource: 'javascript:alert(1)' }, 400);
  await call('teacher', `teachers/bookings/${reservation.id}/notes`, { notes: 'Homework', resource: 'https://example.com/material' });
  assert.equal((await call('student', 'students/overview')).bookings[0].notes, 'Homework');
  await call('student', `students/bookings/${reservation.id}/messages`, { body: 'Hello teacher' });
  assert.equal((await call('teacher', `teachers/bookings/${reservation.id}/messages`)).messages[0].body, 'Hello teacher');
  await call('other', `students/bookings/${reservation.id}/messages`, undefined, 404);
  // Persistent conversations are earned through bookings, private, and retained afterwards.
  const thread = (await call('student', 'students/chat/threads')).threads[0];
  assert.equal(thread.peer.id, teacher.id);
  assert.equal((await call('teacher', 'teachers/chat/threads')).threads[0].id, thread.id);
  assert.equal((await call('other', 'students/chat/threads')).threads.length, 0);
  await call('other', `students/chat/threads/${thread.id}`, undefined, 404);
  await call('owner', 'admin/chat/threads', undefined, 403);
  const dmPath = `students/chat/threads/${thread.id}`;
  const teacherDmPath = `teachers/chat/threads/${thread.id}`;
  const messageId = crypto.randomUUID();
  await call('student', `${dmPath}/messages`, { id: messageId, body: 'سؤال خارج وقت الحصة' });
  await call('student', `${dmPath}/messages`, { id: messageId, body: 'سؤال خارج وقت الحصة' });
  assert.equal((await call('teacher', teacherDmPath)).messages.length, 1, 'Retrying delivery must not duplicate a message');
  assert.equal((await call('teacher', 'teachers/chat/threads')).threads[0].unread, 1);
  await call('teacher', `${teacherDmPath}/read`, { messageId });
  assert.equal((await call('teacher', 'teachers/chat/threads')).threads[0].unread, 0);
  assert.ok((await call('student', dmPath)).thread.peerReadAt > 0);
  await call('teacher', 'teachers/chat/settings', { readReceipts: false, showPresence: false });
  await call('teacher', 'teachers/chat/presence', { active: true });
  let privateThread = (await call('student', dmPath)).thread;
  assert.equal(privateThread.peerReadAt, null);
  assert.equal(privateThread.peer.status, 'hidden');
  assert.equal(privateThread.peer.lastSeen, null);
  await call('teacher', 'teachers/chat/settings', { showPresence: true });
  assert.equal((await call('student', dmPath)).thread.peer.status, 'online');
  await call('teacher', 'teachers/chat/presence', { active: false });
  assert.equal((await call('student', dmPath)).thread.peer.status, 'away');
  await call('teacher', `${teacherDmPath}/typing`, { active: true });
  assert.equal((await call('student', dmPath)).thread.typing, true);
  await call('teacher', `${teacherDmPath}/typing`, { active: false });
  assert.equal((await call('student', dmPath)).thread.typing, false);
  await call('teacher', `${teacherDmPath}/reaction`, { messageId, emoji: '❤️', active: true });
  await call('teacher', `${teacherDmPath}/reaction`, { messageId, emoji: '❤️', active: true });
  assert.deepEqual((await call('student', dmPath)).messages[0].reactions, [{ emoji: '❤️', count: 1, mine: false }]);
  await call('teacher', `${teacherDmPath}/reaction`, { messageId, emoji: '❤️', active: false });
  const replyId = crypto.randomUUID();
  await call('teacher', `${teacherDmPath}/messages`, { id: replyId, body: 'أهلاً', reply_to: messageId });
  assert.equal((await call('student', dmPath)).messages[1].reply.id, messageId);
  await call('student', `${dmPath}/messages`, { id: crypto.randomUUID(), media_url: 'javascript:alert(1)' }, 400);
  await call('student', `${dmPath}/messages`, { id: crypto.randomUUID(), media_url: 'https://evil.test/a.gif' }, 400);
  await call('student', `${dmPath}/messages`, { id: crypto.randomUUID(), media_url: 'https://media.giphy.com/media/111ebonMs90YLu/giphy.gif' });
  await call('student', `${dmPath}/preferences`, { muted: true, blocked: true });
  assert.equal((await call('student', dmPath)).thread.muted, true);
  await call('teacher', `${teacherDmPath}/messages`, { id: crypto.randomUUID(), body: 'blocked' }, 403);
  await call('student', `${dmPath}/messages`, { id: crypto.randomUUID(), body: 'blocked' }, 403);
  assert.equal((await call('teacher', teacherDmPath)).thread.typing, false);
  assert.equal((await call('teacher', teacherDmPath)).thread.peer.status, 'hidden');
  await call('student', `${dmPath}/preferences`, { blocked: false });
  const countBeforeDelete = (await call('teacher', teacherDmPath)).messages.length;
  await call('student', `${dmPath}/delete`, {});
  assert.equal((await call('student', dmPath)).messages.length, 0);
  assert.equal((await call('student', 'students/chat/threads')).threads[0].hidden, true);
  assert.equal((await call('teacher', teacherDmPath)).messages.length, countBeforeDelete);
  await call('student', `${dmPath}/restore`, {});
  assert.equal((await call('student', dmPath)).messages.length, 0, 'Restoring a thread must not restore deleted history');
  await new Promise(resolve => setTimeout(resolve, 2));
  await call('teacher', `${teacherDmPath}/messages`, { id: crypto.randomUUID(), body: 'رسالة جديدة' });
  assert.equal((await call('student', dmPath)).messages.length, 1);
  await call('owner', `admin/bookings/${reservation.id}/payment`, { paid: 1, reference: 'Receipt 001' });
  await call('teacher', `teachers/bookings/${reservation.id}/complete`, {}, 409);
  await call('student', `students/bookings/${reservation.id}/cancel`, {});
  assert.equal((await call('student', 'students/chat/threads')).threads.length, 1, 'The conversation survives a cancelled or finished lesson');
  assert.equal((await call('student', 'students/reminders')).bookings.length, 0);
  await call('student', `students/bookings/${reservation.id}/room`, undefined, 403);
  const second = await call('other', `students/slots/${slot.id}`, {});
  assert.notEqual((await call('other', `students/bookings/${second.id}/room`)).room, studentRoom.room);
  await call('student', `students/bookings/${reservation.id}/cancel`, {}, 409);
  assert.equal((await call('student', 'students/slots')).slots.length, 0);
  await call('owner', `admin/users/${student.id}`, { status: 'suspended' });
  await call('student', 'students/overview', undefined, 401);
  await call('student', 'auth/login', credentials('student@test.com', 'students'), 403);
  await call('other', 'students/profile', { name: 'Evil', subject: '', bio: '' }, 403, { origin: 'https://evil.test' });
  await call('other', 'auth/logout?portal=students', {});
  await call('other', 'students/overview', undefined, 401);
  assert.ok((await call('owner', 'admin/audit')).events.length >= 4);
  const accountList = await call('owner', 'admin/users');
  assert.ok(accountList.users.every(u => !('password' in u) && !('temporaryPassword' in u)));
  const otherId = accountList.users.find(u => u.email === 'other@test.com').id;
  await call('other', 'auth/login', credentials('other@test.com', 'students'));
  await call('other', `admin/users/${teacher.id}/reset-password`, { adminPassword: 'Long-test-password-123' }, 401);
  await call('owner', `admin/users/${otherId}/reset-password`, { adminPassword: 'Wrong-password-123' }, 403);
  await call('owner', 'admin/users/platform-owner/reset-password', { adminPassword: 'Long-test-password-123' }, 404);
  const reset = await call('owner', `admin/users/${otherId}/reset-password`, { adminPassword: 'Long-test-password-123' });
  assert.ok(reset.temporaryPassword.length >= 24 && reset.expires > Date.now());
  await call('other', 'students/overview', undefined, 401);
  await call('other', 'auth/login', credentials('other@test.com', 'students'), 401);
  const temporaryLogin = await call('other', 'auth/login', { ...credentials('other@test.com', 'students'), password: reset.temporaryPassword });
  assert.equal(temporaryLogin.user.mustChangePassword, true);
  await call('other', 'students/overview', undefined, 403);
  await call('other', 'students/profile', undefined, 403);
  await call('other', 'students/reminders', undefined, 403);
  await call('other', 'students/password', { current: reset.temporaryPassword, password: reset.temporaryPassword }, 400);
  await call('other', 'students/password', { current: reset.temporaryPassword, password: 'My-new-password-456' });
  await call('other', 'auth/login', { ...credentials('other@test.com', 'students'), password: reset.temporaryPassword }, 401);
  assert.equal((await call('other', 'auth/login', { ...credentials('other@test.com', 'students'), password: 'My-new-password-456' })).user.mustChangePassword, false);
  await call('other', 'students/overview');
  assert.ok(!(await call('owner', 'admin/users')).users.some(u => JSON.stringify(u).includes(reset.temporaryPassword)));
  const expired = await call('owner', `admin/users/${teacher.id}/reset-password`, { adminPassword: 'Long-test-password-123' });
  DB.db.prepare('UPDATE users SET temporary_password_expires=? WHERE id=?').run(Date.now() - 1, teacher.id);
  await call('teacher', 'auth/login', { ...credentials('teacher@test.com', 'teachers'), password: expired.temporaryPassword }, 401);
  const developmentPassword = 'Development-test-password-789';
  env.DEVELOPMENT_LOGIN_HASH = await passwordHash(developmentPassword);
  env.DEVELOPMENT_LOGIN_EXPIRES = String(Date.now() + 3600000);
  const teacherPasswordBefore = DB.db.prepare('SELECT password FROM users WHERE id=?').get(teacher.id).password;
  assert.equal((await call('teacherDev', 'auth/login', { ...credentials('teacher@test.com', 'teachers'), password: developmentPassword })).user.mustChangePassword, false);
  await call('teacherDev', 'teachers/overview');
  await call('teacherDev', 'admin/users', undefined, 401);
  assert.equal((await call('teacherDev', 'teachers/profile')).user.mustChangePassword, false);
  assert.equal(DB.db.prepare('SELECT password FROM users WHERE id=?').get(teacher.id).password, teacherPasswordBefore);
  await call('studentDev', 'auth/login', { ...credentials('other@test.com', 'students'), password: developmentPassword });
  await call('studentDev', 'students/overview');
  await call('ownerDev', 'auth/login', { ...credentials('owner@test.com', 'admin'), password: developmentPassword }, 401);
  await call('wrongPortal', 'auth/login', { ...credentials('other@test.com', 'teachers'), password: developmentPassword }, 401);
  await call('missing', 'auth/login', { ...credentials('missing@test.com', 'students'), password: developmentPassword }, 401);
  await call('suspended', 'auth/login', { ...credentials('student@test.com', 'students'), password: developmentPassword }, 403);
  env.DEVELOPMENT_LOGIN_EXPIRES = String(Date.now() - 1);
  await call('teacherDev', 'teachers/overview', undefined, 401);
  await call('studentDev', 'auth/login', { ...credentials('other@test.com', 'students'), password: developmentPassword }, 401);
  await call('other', 'auth/login', { ...credentials('other@test.com', 'students'), password: 'My-new-password-456' });
  await call('other', 'students/overview');
  env.DEVELOPMENT_LOGIN_EXPIRES = String(Date.now() + 3600000);
  env.DEVELOPMENT_LOGIN_HASH = await passwordHash('Rotated-development-password');
  await call('studentDev', 'students/overview', undefined, 401);
  delete env.DEVELOPMENT_LOGIN_HASH;
  await call('teacherDev', 'auth/login', { ...credentials('teacher@test.com', 'teachers'), password: developmentPassword }, 401);
  DB.db.close();
});
